PACKAGE = LC_meter
PROGRAMS = LC_meter

prefix ?= /usr
libdir = ${prefix}/lib
datadir = ${prefix}/share

NAME = $(PACKAGE)

target = pic14
chip = 16f876a
SERIAL_PORT = /dev/ttyS0

VERSION_MAJOR = 0
VERSION_MINOR = 9
VERSION_PATCH = 1

CHIP = 16F876A

SERIAL_PORT = /dev/ttyS0
_XTAL_FREQ = 18432000

LC_meter_SOURCES = LC-meter.c delay.c lcd44780.c display.c

chipu := $(shell echo "${CHIP}" | tr "[[:lower:]]" "[[:upper:]]")
chipl := $(shell echo "${CHIP}" | tr "[[:upper:]]" "[[:lower:]]")