PACKAGE = LC_meter
PROGRAMS = LC_meter

NAME = $(PACKAGE)

target = pic14
chip = 16f876a
serialport = /dev/ttyS0

VERSION_MAJOR = 0
VERSION_MINOR = 9
VERSION_PATCH = 1

CHIP = 16F876A

LC_meter_SOURCES = LC-meter.c delay.c lcd44780.c display.c
