PROGRAMS = pictest pictest2 pictest3

pictest_SOURCES = pictest.c delay.c lcd44780.c uart.c adc.c ledsense.c onewire.c ds18b20.c
pictest2_SOURCES = pictest2.c adc.c delay.c lcd44780.c pwm.c  onewire.c ds18b20.c
pictest3_SOURCES = pictest3.c pwm.c adc.c delay.c lcd44780.c