# Generated by:
#  genmakefile -t xc8 -m gmake -DUSE_UART=1 -DUSE_HD44780_LCD=1 -DUSE_TIMER0=1 -DUSE_TIMER1=1 -DUSE_TIMER2=1 --preproc=./cpp-xc8.exe -DMCHP_XC8=1 -D__XC=1 -I. -Ilib -Isrc lib src LC-meter.c --no-create-libs --release --chip=16f876a -o xc8-16f876a-release.mk
DEFS = -DUSE_UART=1 -DUSE_HD44780_LCD=1 -DUSE_TIMER0=1 -DUSE_TIMER1=1 -DUSE_TIMER2=1 -D__XC=1
CC = xc8
CXX = c++
CPPFLAGS = -DNDEBUG=1 -DPIC16=1 -DPIC16F876A=1 -D__$(CHIP)=1 -I. -Ilib -Isrc
CFLAGS = -O2 --mode=pro --float=24 --double=32 --opt=default,+asm,+asmfile,+speed,-space,-debug,9 -q --asmlist --chip=$(CHIP) --errformat="%f:%l:%c error [%n]: %s" --warnformat="%f:%l:%c warning [%n]: %s" --errformat="%f:%l:%c error [%n]: %s" --warnformat="%f:%l:%c warning [%n]: %s"
LINK = mplink
LIB = mplib
TARGET = pic16
CHIP = 16f876a
LDFLAGS = --output=default,-inhx032,+inhx32 --summary=default,+psect --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,+download,+clib --output=-default,elf,+mcof --stack=compiled
CPP = ./cpp-xc8.exe -DMCHP_XC8=1 -D__XC=1

all: build/xc8-16f876a/Release build/xc8-16f876a/Release/LC-meter.cof
build/xc8-16f876a/Release:
	test -d "$@" || mkdir -p "$@"

.c.p1:
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/uart.p1: lib/uart.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/timer.p1: lib/timer.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/ser.p1: lib/ser.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/lcd5110.p1: lib/lcd5110.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/lcd44780.p1: lib/lcd44780.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/format.p1: lib/format.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/delay.p1: lib/delay.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/comparator.p1: lib/comparator.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/buffer.p1: lib/buffer.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/adc.p1: lib/adc.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/lib.lib: build/xc8-16f876a/Release/uart.p1 build/xc8-16f876a/Release/timer.p1 build/xc8-16f876a/Release/ser.p1 build/xc8-16f876a/Release/lcd5110.p1 build/xc8-16f876a/Release/lcd44780.p1 build/xc8-16f876a/Release/format.p1 build/xc8-16f876a/Release/delay.p1 build/xc8-16f876a/Release/comparator.p1 build/xc8-16f876a/Release/buffer.p1 build/xc8-16f876a/Release/adc.p1
	$(LIB) /out:$@ $^

build/xc8-16f876a/Release/print.p1: src/print.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/measure.p1: src/measure.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/src.lib: build/xc8-16f876a/Release/print.p1 build/xc8-16f876a/Release/measure.p1
	$(LIB) /out:$@ $^

build/xc8-16f876a/Release/LC-meter.pp.c: LC-meter.c
	$(CPP) $(CPPFLAGS) $(DEFS) "$<" -o"$@"

build/xc8-16f876a/Release/LC-meter.p1: build/xc8-16f876a/Release/LC-meter.pp.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c "$<" -o"$@"

build/xc8-16f876a/Release/LC-meter.cof: build/xc8-16f876a/Release/LC-meter.p1 build/xc8-16f876a/Release/uart.p1 build/xc8-16f876a/Release/timer.p1 build/xc8-16f876a/Release/ser.p1 build/xc8-16f876a/Release/lcd5110.p1 build/xc8-16f876a/Release/lcd44780.p1 build/xc8-16f876a/Release/format.p1 build/xc8-16f876a/Release/delay.p1 build/xc8-16f876a/Release/comparator.p1 build/xc8-16f876a/Release/buffer.p1 build/xc8-16f876a/Release/adc.p1 build/xc8-16f876a/Release/print.p1 build/xc8-16f876a/Release/measure.p1
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(LDFLAGS) -o"$@"  $^ $(LIBS) $(EXTRA_LIBS) $(STDC_LIBS)

clean:
	rm -f build/xc8-16f876a/Release/*.p1
	rm -f build/xc8-16f876a/Release/*.lib
	rm -f build/xc8-16f876a/Release/*.c
	rm -f build/xc8-16f876a/Release/*.cof

